"""Regenerate notebooks/<module>.ipynb from app/<module>.py.

Each top-level function/class becomes its own cell so you can print/test in
the middle. Code is byte-identical to the .py except one mechanical rewrite:
relative imports (`from . import x`, `from .mod import y`) become absolute
(`from app import x`) so the cells can run outside the package.

Re-run after editing any .py:   python notebooks/build_notebooks.py
"""
import ast
import json
import re
import uuid
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "notebooks"

PREAMBLE = """\
# --- notebook preamble (not part of the module) -------------------------
# Make the repo root importable so `from app import ...` works, no matter
# where jupyter was started.
import sys
from pathlib import Path
_ROOT = Path.cwd()
while not (_ROOT / 'app').is_dir():
    if _ROOT.parent == _ROOT:
        raise RuntimeError('Run this notebook from inside the RepoProof repo')
    _ROOT = _ROOT.parent
sys.path.insert(0, str(_ROOT))
"""

def rewrite_imports(src: str):
    return re.subn(
        r"^from \.(\w*)",
        lambda m: ("from app." + m.group(1)) if m.group(1) else "from app",
        src, flags=re.M,
    )

def split_cells(src: str) -> list[str]:
    """Split at top-level def/class boundaries (incl. decorators and the
    comment block directly above). Concatenating the cells reproduces the
    source exactly."""
    lines = src.splitlines(keepends=True)
    starts = []
    for node in ast.parse(src).body:
        if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef, ast.ClassDef)):
            s = node.lineno
            if node.decorator_list:
                s = min(d.lineno for d in node.decorator_list)
            i = s - 2
            while i >= 0 and lines[i].lstrip().startswith("#"):
                s = i + 1
                i -= 1
            starts.append(s)
    cells, prev = [], 0
    for s in sorted(set(starts)):
        seg = "".join(lines[prev:s - 1])
        if seg.strip():
            cells.append(seg)
        prev = s - 1
    tail = "".join(lines[prev:])
    if tail.strip():
        cells.append(tail)
    return cells

def md(text): return {"cell_type": "markdown", "id": uuid.uuid4().hex[:8], "metadata": {}, "source": text}
def code(text): return {"cell_type": "code", "id": uuid.uuid4().hex[:8], "metadata": {},
                        "execution_count": None, "outputs": [], "source": text}

def build(py: Path) -> Path:
    src = py.read_text()
    rewritten, n_imports = rewrite_imports(src)
    cells = [
        md(f"# `app/{py.name}` — editable notebook copy\n\n"
           f"Generated by `notebooks/build_notebooks.py`. Code is identical to the .py"
           + (f" except **{n_imports} relative import(s)** rewritten to `from app ...` so cells can run.\n" if n_imports else ".\n")
           + "\nOne cell per top-level function/class — add `print(...)`/test cells anywhere.\n"
           + "**Note:** edits here do NOT write back to the .py; copy changes across manually."),
        code(PREAMBLE),
    ]
    segs = split_cells(rewritten)
    assert "".join(segs) == rewritten, f"fidelity check failed for {py.name}"
    cells += [code(s) for s in segs]
    nb = {"cells": cells,
          "metadata": {"kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
                       "language_info": {"name": "python", "version": "3"}},
          "nbformat": 4, "nbformat_minor": 5}
    out = OUT / (py.stem + ".ipynb")
    out.write_text(json.dumps(nb, indent=1, ensure_ascii=False))
    return out

if __name__ == "__main__":
    for py in sorted((ROOT / "app").glob("*.py")):
        if py.name == "__init__.py":
            continue
        out = build(py)
        print("wrote", out.relative_to(ROOT))
